services:
  - type: web
    name: yomu-gamification-engine
    env: docker
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: APP_PORT
        value: "8081"
      - key: CLOUDAMQP_URL
        sync: false
      - key: DATABASE_URL
        sync: false
