services:
  - type: web
    name: yomu-gamification-engine
    runtime: docker
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: CLOUDAMQP_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GATEWAY_SHARED_SECRET
        sync: false
      - key: RUST_LOG
        value: info